data/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='data'

urlpatterns = [
    path('', tabel_data, name="tabel_data"),
    path('tambah-data/', tambah_data, name="tambah_data"),
    path('tambah-data-kegiatan/', tambah_data_kegiatan, name="tambah_data_kegiatan"),
]

kegiatan/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='kegiatan'

urlpatterns = [
    path('', tabel_kegiatan, name="tabel_kegiatan"),
    # path('create-forward-cpm/', create_forwardsCPM, name='create_forwardsCPM'), # create dari Python
    # path('create-backward-cpm/', create_backwardsCPM, name='create_backwardsCPM'), # create dari Python
    path('create-cpm/', create_cpm, name='create_cpm'), # create dari Python
    path('export-cpm/', export_excel, name='export_excel'),
    path('tambah-kegiatan/', tambah_kegiatan, name="tambah_kegiatan"),
    path('tabel-pert/', tabel_pert, name="tabel_pert"),
    path('tambah-pert/', tambah_pert, name="tambah_pert"),
    path('tabel-cpm/', tabel_cpm, name='tabel_cpm'),
    path('tambah-cpm/', tambah_cpm, name='tambah_cpm'),
    path('table-biaya/', tabel_estimasi_biaya, name="tabel_estimasi_biaya"),
    # path('estimasi-biaya/', estimasi_biaya, name="estimasi_biaya"),
    path('tabel-schedule/', tabel_schedule, name="tabel_schedule"), # formset 2 input progress + 1 input minggu
    path('tambah-schedule/', tambah_schedule, name="tambah_schedule"),
]

spkproyeksiumkt/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/profile/', account_profile, name='account_profile'),
    path('accounts/profile/', include('accounts.urls')),
    path('data/', include('data.urls')),
    path('proyek/', include('proyek.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

data/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import *
from proyek.models import *

# Create your models here.
class Data(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=False, null=True)
    proyek = models.ForeignKey(Proyek, on_delete=models.CASCADE, blank=False, null=True)
    # nama_data = models.CharField(_("Nama Data"), max_length=255, blank=True, null=True)
    # waktu = models.DateTimeField(auto_now_add=False)
    waktu = models.CharField(_("Waktu"), max_length=20, blank=True, null=True)
    # biaya = models.DecimalField(max_digits=100, decimal_places=2)
    biaya = models.CharField(_("Biaya"), max_length=30, blank=True, null=True)

    class Meta:
        ordering = ('user',)
        verbose_name = 'Data'
        verbose_name_plural = 'Data'

    # def __str__(self):
    #     return self.proyek
        # return str(self.proyek)

data/forms.py
from django import forms
from django.contrib.auth.models import *
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext as _

from .models import *
from kegiatan.models import *


######################################################################################################
class Data_Form(forms.Form):

    user = forms.CharField(required=False, label="User:", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    proyek = forms.CharField(required=False, label="Proyek:", widget=forms.TextInput(attrs={'class': "form-control"}))
    waktu = forms.CharField(required=False, label="Waktu:", widget=forms.TextInput(attrs={'class': "form-control"}))
    biaya = forms.CharField(required=False, label="Biaya:", widget=forms.TextInput(attrs={'class': "form-control"}))


class Data_ModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    # user = forms.CharField(required=False, label="User:", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    # proyek = forms.CharField(required=False, label="Proyek:", widget=forms.TextInput(attrs={'class': "form-control"}))
    # waktu = forms.CharField(required=False, label="Waktu:", widget=forms.TextInput(attrs={'class': "form-control"}))
    # biaya = forms.CharField(required=False, label="Biaya:", widget=forms.TextInput(attrs={'class': "form-control"}))

    class Meta:
        model = Data
        fields = ('user', 'proyek', 'waktu', 'biaya')
        widgets = {
            # 'user': forms.HiddenInput(),
        }


class Kegiatan_Form(forms.Form):
    # user = forms.CharField(required=False, label="User:", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    proyek = forms.CharField(required=False, label="Proyek:", widget=forms.TextInput(attrs={'class': "form-control"}))
    nama_kegiatan = forms.CharField(required=False, label="Nama Kegiatan:", widget=forms.TextInput(attrs={'class': "form-control"}))
    kode = forms.CharField(required=False, label="Kode Kegiatan:", widget=forms.TextInput(attrs={'class': "form-control"}))
    bobot_kegiatan = forms.CharField(required=False, label="Bobot Kegiatan:", widget=forms.TextInput(attrs={'class': "form-control"}))
    estimasi_biaya = forms.CharField(required=False, label="Schedule:", widget=forms.TextInput(attrs={'class': "form-control"}))
    estimasi_waktu = forms.CharField(required=False, label="Tipe Estimasi:", widget=forms.TextInput(attrs={'class': "form-control"}))

data/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render, HttpResponseRedirect, get_object_or_404
from django.shortcuts import render, get_object_or_404
from django.utils.translation import gettext_lazy as _

from .models import *
from .forms import *

from accounts.models import *
from proyek.models import *

def tabel_data(request):
    page_title = _('Data')
    data_proyek = Data.objects.filter()

    context = {
        'page_title': page_title,
        'data_proyek': data_proyek,
    }
    return render(request,'data/tabel_data.html', context)

def tambah_data(request):
    page_title = _('Tambah Data')
    data_user =   UserProfile.objects.all()
    data_proyek = Proyek.objects.filter()
    # data_proyek = get_object_or_404(Proyek, slug=category_slug)

    if request.method == 'POST':
        # form = Data_Form(request.POST or None)
        form = Data_ModelForm(request.POST or None)

        if form.is_valid():
            # profile = Data()
            profile = form.save(commit=False)
            profile.user = form.cleaned_data['user']
            profile.proyek = form.cleaned_data['proyek']
            profile.waktu = form.cleaned_data['waktu']
            profile.save()

            messages.success(request, _('Your Data has been change successfully.'))
            return redirect('data:tabel_data')
        else:
            messages.warning(request, form.errors)

    else:
        # form = Data_Form()
        form = Data_ModelForm()

    context = {
        'page_title': page_title,
        'form': form,
    }

    return render(request,'data/tambah_data.html', context)

def tambah_data_kegiatan(request):
    page_title = _('Tambah Data Kegiatan')
    data_user =   UserProfile.objects.all()
    data_proyek = Proyek.objects.filter()
    # data_proyek = get_object_or_404(Proyek, slug=category_slug)
    data_kegiatan = Kegiatan.objects.filter()

    if request.method == 'POST':
        form = Kegiatan_Form(request.POST or None)

        if form.is_valid():
            # profile = Data()
            profile = form.save(commit=False)
            profile.user = form.cleaned_data['user']
            profile.proyek = form.cleaned_data['proyek']
            profile.waktu = form.cleaned_data['waktu']
            profile.save()

            messages.success(request, _('Your Data has been change successfully.'))
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, form.errors)

    else:
        form = Kegiatan_Form()

    context = {
        'page_title': page_title,
        'form': form,
    }

    return render(request,'data/tambah_data_kegiatan.html', context)

templates/data/daftar_data.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6"></div>
		<div class="col-4">
			<h4>Data Overview</h4>
		</div>
		<div class="col-2"></div>
	</div>
	<div class="row">
		<div class="col-md-3 col-sm-4">
			<div class="link-tiles">
				<a href="{% url 'data:tambah_data' %}" class="add_cart"><i class="fa fa-plus" aria-hidden="true"></i> Tambah Data</a>
			</div>
		</div>

		<div class="col-lg-8 col-md-8 col-sm-6">
			<form method="post" action="">
			{% csrf_token %}
				<table id="t_add_row" class="table table-striped table-bordered">
					<thead class="thead_light">
						<tr>
							<th class="text-center">{% trans "ID" %}</th>
							<th class="text-center">{% trans "User" %}</th>
							<th class="text-center">{% trans "Proyek" %}</th>
						</tr>
					</thead>
					<tbody>
						{% for item in data_proyek %}
						<tr>
							<td>{{ item.id }}</td>
							<td>{{ item.user }}</td>
							<td>{{ item.proyek }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</form>
		</div>
	</div>
</div>

{% endblock %}

		<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}

templates/data/tabel_data.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6"></div>
		<div class="col-4">
			<h4>Tabel Data</h4>
		</div>
		<div class="col-2"></div>
	</div>
	<div class="row">
		<div class="col-md-3 col-sm-4">
			<div class="link-tiles">
				<a href="{% url 'data:tambah_data' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Tambah User</a>
			</div>
			<div class="link-tiles">
				<a href="{% url 'kegiatan:tambah_kegiatan' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Tambah Kegiatan</a>
			</div>
			<div class="link-tiles">
				<a href="{% url 'kegiatan:tambah_pert' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Tambah PERT</a>
			</div>
			<div class="link-tiles">
				<a href="{% url 'kegiatan:export_excel' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Persiapan CPM </a>
			</div>
			<div class="link-tiles">
				<a href="{% url 'kegiatan:create_cpm' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Buat CPM </a>
			</div>
			<div class="link-tiles">
				<a href="{% url 'kegiatan:tambah_schedule' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Tambah Schedule</a>
			</div>
		</div>

		<div class="col-lg-8 col-md-8 col-sm-6">
			<form method="post" action="">
			{% csrf_token %}
				<table id="t_add_row" class="table table-striped table-bordered">
					<thead class="thead_light">
						<tr>
							<th class="text-center">{% trans "ID" %}</th>
							<th class="text-center">{% trans "User" %}</th>
							<th class="text-center">{% trans "Proyek" %}</th>
						</tr>
					</thead>
					<tbody>
						{% for item in data_proyek %}
						<tr>
							<td class="text-center">{{ item.id }}</td>
							<td class="text-center">{{ item.user }}</td>
							<td class="text-center">{{ item.proyek }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</form>
		</div>
	</div>
</div>

{% endblock %}

		<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}

templates/data/tambah_data.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="flex-inline">
                <div class="heading-small-v-2">Tambah Data</div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
                {% csrf_token %}
                    <div class="mb-3">
                        {{ form.user|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.proyek|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}

templates/data/tambah_data0.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="flex-inline">
                <div class="heading-small-v-2">Tambah Data</div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
                {% csrf_token %}
                    {{ form.user|as_crispy_field }}
                    <div class="mb-3">
                        {{ form.proyek|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.waktu|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.biaya|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}

templates/data/tambah_data_kegiatan.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-lg-8 col-md-8 col-sm-12">
            <div class="flex-inline">
                <div class="heading-small-v-2">Tambah Data</div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
                {% csrf_token %}
                    <div class="mb-3">
                        {{ form.user|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.proyek|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}