data/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='data'

urlpatterns = [
    path('', tabel_data, name="tabel_data"),
    path('tambah-data/', tambah_data, name="tambah_data"),
    path('tambah-data-kegiatan/', tambah_data_kegiatan, name="tambah_data_kegiatan"),
]

kegiatan/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='kegiatan'

urlpatterns = [
    path('', tabel_kegiatan, name="tabel_kegiatan"),
    # path('create-forward-cpm/', create_forwardsCPM, name='create_forwardsCPM'), # create dari Python
    # path('create-backward-cpm/', create_backwardsCPM, name='create_backwardsCPM'), # create dari Python
    path('create-cpm/', create_cpm, name='create_cpm'), # create dari Python
    path('export-cpm/', export_excel, name='export_excel'),
    path('tambah-kegiatan/', tambah_kegiatan, name="tambah_kegiatan"),
    path('tabel-pert/', tabel_pert, name="tabel_pert"),
    path('tambah-pert/', tambah_pert, name="tambah_pert"),
    path('tabel-cpm/', tabel_cpm, name='tabel_cpm'),
    path('tambah-cpm/', tambah_cpm, name='tambah_cpm'),
    path('table-biaya/', tabel_estimasi_biaya, name="tabel_estimasi_biaya"),
    # path('estimasi-biaya/', estimasi_biaya, name="estimasi_biaya"),
    path('tabel-schedule/', tabel_schedule, name="tabel_schedule"), # formset 2 input progress + 1 input minggu
    path('tambah-schedule/', tambah_schedule, name="tambah_schedule"),
]

spkproyeksiumkt/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/profile/', account_profile, name='account_profile'),
    path('accounts/profile/', include('accounts.urls')),
    path('data/', include('data.urls')),
    path('proyek/', include('proyek.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

kegiatan/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import UserProfile
from proyek.models import Proyek
from .choices import *

import os
import uuid


# Create your models here.
class Kegiatan(models.Model):
	# user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=False, null=True)
	proyek = models.ForeignKey(Proyek, on_delete=models.CASCADE, blank=False, null=True)
	nama_kegiatan = models.CharField(_("Nama Kegiatan"), max_length=255, blank=False, null=True)
	kode = models.CharField(max_length=255, choices=KODE_CHOICES, default="-", blank=True, null=True)
	bobot_kegiatan = models.DecimalField(_("Bobot Kegiatan"), max_digits=3, decimal_places=2, blank=True, null=True)
	biaya_kegiatan = models.DecimalField(_("Biaya Kegiatan"), max_digits=10, decimal_places=0, blank=True, null=True)
	predecessor = models.CharField(max_length=255, choices=PREDECESSOR_CHOICES, default="-", blank=True, null=True)
	hubungan_keterkaitan = models.CharField(max_length=255, choices=KONSTRAIN_CHOICES, default="ss", null=True, blank=True)
	duration = models.FloatField(blank=True, null=True)

	class Meta:
		ordering = ('id',)
		verbose_name = 'Kegiatan'
		verbose_name_plural = 'Kegiatan'

	def __str__(self):
	#     return str(self.id)
		# return self.nama_kegiatan
		# return self.kode
		return str(self.nama_kegiatan)
		# return f"{self.kode} - {self.nama_kegiatan}"


class PERT(models.Model):
	kegiatan = models.OneToOneField(Kegiatan, on_delete=models.CASCADE, blank=False, null=True)
	duration = models.FloatField(blank=True, null=True)
	optimistic_time = models.FloatField(_("Optimistic Time"), blank=True, null=True)
	most_likely_time = models.FloatField(_("Most Likely Time"), blank=True, null=True)
	pessimistic_time = models.FloatField(_("Pessimistic Time"), blank=True, null=True)
	standar_deviasi = models.FloatField(_("Standar Deviasi"), blank=True, null=True)
	varians_kegiatan = models.FloatField(_("Varians Kegiatan"), blank=True, null=True)


	class Meta:
		ordering = ('id',)
		verbose_name = 'PERT'
		verbose_name_plural = 'PERT'

	def __str__(self):
		return str(self.id)


class CPM(models.Model):
	kegiatan = models.CharField(max_length=255, blank=True, null=True)
	kode = models.CharField(max_length=255, choices=KODE_CHOICES, default="-", blank=True, null=True)
	duration = models.FloatField(blank=True, null=True)
	predecessor = models.CharField(max_length=255, choices=PREDECESSOR_CHOICES, default="-", blank=True, null=True)
	earliest_start = models.FloatField(_("ES"), blank=True, null=True)
	earliest_finish = models.FloatField(_("EF"), blank=True, null=True)
	latest_start = models.FloatField(_("LS"), blank=True, null=True)
	latest_finish = models.FloatField(_("LF"), blank=True, null=True)
	slack_time = models.FloatField(_("Slack"), blank=True, null=True)
	critical = models.CharField(max_length=255, blank=True, null=True)
	successors = models.CharField(max_length=255, blank=True, null=True)

	class Meta:
		ordering = ('id',)
		verbose_name = 'CPM'
		verbose_name_plural = 'CPM'

	# def __str__(self):
	#     return str(self.id)
		# return self.nama_kegiatan
		# return self.kode
		# return str(self.nama_kegiatan)
		# return f"{self.kode} - {self.nama_kegiatan}"


class Schedule(models.Model):
	minggu = models.IntegerField(_("Minggu"), blank=True, null=True)
	progress_rencana = models.FloatField(_("Progress Rencana"), blank=True, null=True)
	progress_aktual = models.FloatField(_("Progress Aktual"), blank=True, null=True)
	acwp = models.DecimalField(_("Actual Cost of Work Planned"), max_digits=10, decimal_places=2, blank=True, null=True)
	bcwp = models.DecimalField(_("Budgeted Cost of Work Planned "), max_digits=10, decimal_places=2, blank=True, null=True)
	bcws = models.DecimalField(_("Budgeted Cost of Work Schedule"), max_digits=10, decimal_places=2, blank=True, null=True)
	cost_variance = models.DecimalField(_("Cost Variance"), max_digits=10, decimal_places=2, blank=True, null=True)
	cost_performance_index = models.FloatField(_("Cost Performance Index"), blank=True, null=True)

	class Meta:
		ordering = ('id',)
		verbose_name = 'Schedule'
		verbose_name_plural = 'Schedule'

	# def __str__(self):
	#     return str(self.id)

	# @property
	# def price_display(self):
	#     return "Rp%s" % self.estimasi_biaya

kegiatan/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _

from .models import *
from .forms import *
from .cpm import *

from proyek.models import *
from proyek.forms import *
from accounts.models import *

import re
import pandas as pd
import numpy as np
import math
import xlwt
import itertools

# Create your views here.
################################# KEGIATAN ########################################
@login_required()
def tabel_kegiatan(request):
	page_title = _('Kegiatan')
	data_user =   UserProfile.objects.all()
	data_kegiatan = Kegiatan.objects.filter()
	total_bobot = Kegiatan.objects.aggregate(Sum('bobot_kegiatan'))
	total_biaya = Kegiatan.objects.aggregate(Sum('biaya_kegiatan'))
	proyek_types = Proyek.objects.all()

	project_id = request.GET.get('project')

	context = {
		'page_title': page_title,
		'data_kegiatan': data_kegiatan,
		'total_bobot': total_bobot,
		'total_biaya': total_biaya,
		'proyek_types': proyek_types,
	}

	return render(request,'kegiatan/tabel_kegiatan.html', context)


#@login_required()
def tambah_kegiatan(request):
	page_title = _('Tambah Kegiatan')
	user_id = request.user.is_authenticated
	data_user =   UserProfile.objects.filter(id=user_id)
	data_kegiatan = Kegiatan.objects.filter()
	data_rab =   Kegiatan.objects.all().values_list("biaya_kegiatan")

	if request.method == 'POST':
		form = Kegiatan_ModelForm(request.POST or None)

		if form.is_valid():
			profile = form.save(commit=False)
			profile.proyek = form.cleaned_data['proyek']
			profile.nama_kegiatan = form.cleaned_data['nama_kegiatan']
			profile.kode = form.cleaned_data['kode']
			profile.bobot_kegiatan = form.cleaned_data['bobot_kegiatan']
			profile.biaya_kegiatan = form.cleaned_data['biaya_kegiatan']
			profile.predecessor = form.cleaned_data['predecessor']
			profile.hubungan_keterkaitan = form.cleaned_data['hubungan_keterkaitan']
			profile.save()

			messages.success(request, _('Your Kegiatan has been save successfully.'))
			return redirect('kegiatan:tabel_kegiatan')
		else:
			messages.warning(request, form.errors)

	else:
		form = Kegiatan_ModelForm(instance=request.user)

	context = {
		'page_title': page_title,
		'data_kegiatan': data_kegiatan,
		'form': form,
	}

	return render(request,'kegiatan/tambah_kegiatan.html', context)


############################### PERT ######################################
def hitungDurasi(a,m,b):
	return (a + (4*m) + b)/6


def hitungDeviasi(a,b):
	return (b-a)/6


def hitungVarians(a,b):
	return pow((b-a)/6,2)


def tabel_pert(request):
	page_title = _('Tabel PERT')
	data_user =   UserProfile.objects.all()
	pert_data = PERT.objects.all()
	total_estimasi_waktu = PERT.objects.aggregate(Sum('duration'))
	total_duration = PERT.objects.aggregate(Sum('duration'))
	varians_kegiatan = PERT.objects.aggregate(Sum('varians_kegiatan'))

	if varians_kegiatan:standar_varians_kejadian = varians_kegiatan.values()
	standar_varians_kejadian = list(varians_kegiatan.values())
	standar_varians_kejadian = standar_varians_kejadian[0]
	if standar_varians_kejadian is None:
		standar_deviasi_kejadian = 0
	else:
		standar_deviasi_kejadian = math.sqrt(standar_varians_kejadian)

	optimistic_time = PERT.objects.all().values_list("optimistic_time")
	most_likely_time = PERT.objects.all().values_list("most_likely_time")
	pessimistic_time = PERT.objects.all().values_list("pessimistic_time")

	optimistic_time = [item for item in optimistic_time]
	most_likely_time = [item for item in most_likely_time]
	pessimistic_time = [item for item in pessimistic_time]

	context = {
		'page_title': page_title,
		'pert_data': pert_data,
		'total_estimasi_waktu': total_estimasi_waktu,
		'optimistic_time': optimistic_time,
		'most_likely_time': most_likely_time,
		'pessimistic_time': pessimistic_time,
		'total_duration': total_duration,
		'varians_kegiatan': varians_kegiatan,
		'standar_deviasi_kejadian': standar_deviasi_kejadian,
	}

	return render(request,'kegiatan/tabel_pert.html', context)


#@login_required()
def tambah_pert(request):
	page_title = _('Tambah PERT')

	user_id = request.user.is_authenticated
	data_user =   UserProfile.objects.filter(id=user_id)
	data_proyek =   Proyek.objects.filter(user=user_id)

	data_rab = Kegiatan.objects.aggregate(Sum('biaya_kegiatan'))
	data_rab = list(data_rab.values())
	data_rab = data_rab[0]

	duration = PERT.objects.aggregate(Sum('duration'))
	duration = list(duration.values())
	duration = duration[0]

	standar_deviasi = PERT.objects.aggregate(Sum('standar_deviasi'))
	standar_deviasi = list(standar_deviasi.values())
	standar_deviasi = standar_deviasi[0]

	varians_kegiatan = PERT.objects.aggregate(Sum('varians_kegiatan'))
	varians_kegiatan = list(varians_kegiatan.values())
	varians_kegiatan = varians_kegiatan[0]

	if request.method == 'POST':
		form = PERT_ModelForm(request.POST or None)

		if form.is_valid():
			estimasi = form.save(commit=False)

			get_select = request.POST.get('kegiatan')
			estimasi.kegiatan = Kegiatan.objects.get(id=get_select)
			estimasi.optimistic_time = form.cleaned_data['optimistic_time']
			estimasi.most_likely_time = form.cleaned_data['most_likely_time']
			estimasi.pessimistic_time = form.cleaned_data['pessimistic_time']
			hitung_Durasi = hitungDurasi(estimasi.optimistic_time, estimasi.most_likely_time, estimasi.pessimistic_time)
			estimasi.duration = hitung_Durasi
			hitung_Deviasi = hitungDeviasi(estimasi.optimistic_time, estimasi.pessimistic_time)
			estimasi.standar_deviasi = hitung_Deviasi
			hitung_Varians = hitungVarians(estimasi.optimistic_time, estimasi.pessimistic_time)
			estimasi.varians_kegiatan = hitung_Varians
			estimasi.save()

			save_kegiatan = Kegiatan.objects.get(id=get_select)
			save_kegiatan.duration = hitung_Durasi
			save_kegiatan.save()

			messages.success(request, _('Your PERT has been save successfully.'))
			return redirect('kegiatan:tabel_pert')
		else:
			messages.warning(request, form.errors)

	else:
		form = PERT_ModelForm(instance=request.user)

	context = {
		'page_title': page_title,
		'form': form,
	}

	return render(request,'kegiatan/tambah_pert.html', context)


################################ CPM ##########################################
def tabel_cpm(request):
	page_title = _('Tabel CPM')
	user_id = request.user.is_authenticated
	data_kegiatan = CPM.objects.all()

	context = {
		'page_title': page_title,
		'data_kegiatan': data_kegiatan,
	}

	return render(request,'kegiatan/tabel_cpm.html', context)


def tambah_cpm(request):
	page_title = _('Tambah CPM')
	is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

	get_select = request.GET.get('get_select')

	if request.method == 'POST':
		get_select = request.POST.get('get_select')
		form = CPM_ModelForm(request.POST or None)

		if form.is_valid():
			estimasi = form.save(commit=False)

			# estimasi.kegiatan = form.cleaned_data['kegiatan']
			# estimasi.optimistic_time = form.cleaned_data['optimistic_time']
			# estimasi.most_likely_time = form.cleaned_data['most_likely_time']
			# estimasi.pessimistic_time = form.cleaned_data['pessimistic_time']
			# hitung_Durasi = hitungDurasi(estimasi.optimistic_time, estimasi.most_likely_time, estimasi.pessimistic_time)
			# estimasi.duration = hitung_Durasi
			# hitung_Deviasi = hitungDeviasi(estimasi.optimistic_time, estimasi.pessimistic_time)
			# estimasi.standar_deviasi = hitung_Deviasi
			# hitung_Varians = hitungVarians(estimasi.optimistic_time, estimasi.pessimistic_time)
			# estimasi.varians_kegiatan = hitung_Varians
			# estimasi.save()

			# obj, update = PERT.objects.update_or_create(kegiatan=estimasi.kegiatan, optimistic_time=estimasi.optimistic_time, most_likely_time=estimasi.most_likely_time, pessimistic_time=estimasi.pessimistic_time)

			# get_select = request.POST.get('get_select')
			# get_select = estimasi.kegiatan.id
			# set_kegiatan = Kegiatan.objects.get(id=get_select)
			# set_kegiatan.duration = hitung_Durasi
			# set_kegiatan.standar_deviasi = hitung_Deviasi
			# set_kegiatan.varians_kegiatan = hitung_Varians

			# set_kegiatan.save()

			messages.success(request, _('Your PERT has been save successfully.'))
			return redirect('kegiatan:tabel_pert')
		else:
			messages.warning(request, form.errors)

	else:
		form = CPM_ModelForm(instance=request.user)

	context = {
		'page_title': page_title,
		'form': form,
	}

	return render(request,'kegiatan/tambah_cpm.html', context)


################################## CPM ####################################
def export_excel(request):
	response = HttpResponse(content_type='application/ms-excel')
	response['Content-Disposition'] = 'attachment; filename="data.xlsx"'

	wb = xlwt.Workbook(encoding='utf-8')
	ws = wb.add_sheet('Sheet1')

	# Sheet header, first row
	row_num = 0

	font_style = xlwt.XFStyle()
	font_style.font.bold = True

	columns = ['Nama Kegiatan', 'Kode', 'Predecessor', 'Durasi', 'ES', 'EF', 'LS', 'LF', 'Slack', 'Lintasan', ]

	for col_num in range(len(columns)):
		ws.write(row_num, col_num, columns[col_num], font_style)

	# Sheet body, remaining rows
	font_style = xlwt.XFStyle()

	rows = Kegiatan.objects.all().values_list('nama_kegiatan', 'kode', 'predecessor', 'duration')
	for row in rows:
		row_num += 1
		for col_num in range(len(row)):
			ws.write(row_num, col_num, row[col_num], font_style)

	# wb.save(response)
	wb.save("/var/www/html/spkproyeksiumkt/kegiatan/data.xlsx")
	# return response
	messages.success(request, _('Your CPM table has been saved to data.xlsx successfully.'))
	return redirect('kegiatan:tabel_cpm')


def create_cpm(request):
	main()
	messages.success(request, _('Your CPM has been created successfully.'))
	return redirect('kegiatan:tabel_cpm')


################################ SCHEDULE & BIAYA ##########################################
def tabel_estimasi_biaya(request):

templates/kegiatan/daftar_estimasi_waktu_new.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6"></div>
		<div class="col-4">
			<h4>Daftar Estimasi Waktu</h4>
		</div>
		<div class="col-2"></div>
	</div>
	<div class="row">
		<div class="col-lg-2 col-md-2 col-sm-4">
			<div class="link-tiles">
				<a href="{% url 'proyek:estimasi_waktu' %}" class="add_cart"><i class="fa fa-plus" aria-hidden="true"></i> Estimasi Waktu</a>
			</div>
		</div>

		<div class="col-lg-10 col-md-10 col-sm-6">
			<table id="t_add_row" class="table table-striped table-bordered">
				{% render_table object_list %}
			</table>
		</div>
	</div>
</div>

{% endblock %}


{% block extra_jscript %}
{% endblock %}

templates/kegiatan/estimasi_waktu.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-6">
            <h4>Tambah PERT</h4>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
                {% csrf_token %}
                    <div class="mb-3">
                        {{ form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
<script type="text/javascript">
$(document).ready(function()
{
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method)
    {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup(
    {
        beforeSend: function(xhr, settings)
        {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain)
            {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        },
    });

    $('#id_tabel_estimasi_waktu_a').change(function()
    {
        var tabel_estimasi_waktu_a = $(this).val();

        console.log("tabel_estimasi_waktu_a", tabel_estimasi_waktu_a);

        $.ajax(
        {
            url: '',
            method: 'POST',
            data: {
                tabel_estimasi_waktu_a,
            },
            success: function(data)
            {
                console.log(id_tabel_estimasi_waktu_a);
            }
        })
    })


    $('select#id_kegiatan').change(function()
    {
        // var get_select = $(this).find(":selected").text();
        var get_select = $(this).find(":selected").val();

        // console.log("get_select", get_select);

        if ($(this).find('option:selected'))
        {
            $.ajax(
            {
                // url: '',
                url: '/kegiatan/estimasi-waktu/?get_select=' + get_select,
                method: 'GET',
                data: {
                    get_select,
                },
                success: function(data)
                {
                    console.log(get_select);
                    // $("#id_nama_kegiatan").val(get_select);
                }
            })
        }
    })
});
</script>
{% endblock %}

templates/kegiatan/tambah_cpm.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-6">
            <h4>Tambah CPM</h4>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
                {% csrf_token %}
                    <div class="mb-3">
                        {{ form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
<script type="text/javascript">
$(document).ready(function()
{
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method)
    {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup(
    {
        beforeSend: function(xhr, settings)
        {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain)
            {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        },
    });

    $('#id_tabel_pert_a').change(function()
    {
        var tabel_pert_a = $(this).val();

        console.log("tabel_pert_a", tabel_pert_a);

        $.ajax(
        {
            url: '',
            method: 'POST',
            data: {
                tabel_pert_a,
            },
            success: function(data)
            {
                console.log(id_tabel_pert_a);
            }
        })
    })


    $('select#id_kegiatan').change(function()
    {
        // var get_select = $(this).find(":selected").text();
        var get_select = $(this).find(":selected").val();

        // console.log("get_select", get_select);

        if ($(this).find('option:selected'))
        {
            $.ajax(
            {
                // url: '',
                url: '/kegiatan/tambah-pert/',
                method: 'POST',
                data: {
                    get_select,
                },
                success: function(data)
                {
                    console.log(get_select);
                    // $("#id_nama_kegiatan").val(get_select);
                }
            })
        }
    })
});
</script>
{% endblock %}

templates/kegiatan/tambah_pert.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-6">
            <h4>Tambah PERT</h4>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
            <div class="col-2">
            </div>
            <div class="col-8">
                <form action="" method="POST" name="get_select" id="get_select" class="get_select">
                {% csrf_token %}
                    <div class="mb-3">
                        {{ form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                </form>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
<script type="text/javascript">
$(document).ready(function()
{
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method)
    {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup(
    {
        beforeSend: function(xhr, settings)
        {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain)
            {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        },
    });

    $('#id_tabel_pert_a').change(function()
    {
        var tabel_pert_a = $(this).val();

        console.log("tabel_pert_a", tabel_pert_a);

        $.ajax(
        {
            url: '',
            method: 'POST',
            data: {
                tabel_pert_a,
            },
            success: function(data)
            {
                console.log(id_tabel_pert_a);
            }
        })
    })


    $('select#id_kegiatan').change(function()
    {
        // var get_select = $(this).find(":selected").text();
        var get_select = $(this).find(":selected").val();

        // console.log("get_select", get_select);

        if ($(this).find('option:selected'))
        {
            $.ajax(
            {
                url: '',
                // url: '/kegiatan/tambah-pert/',
                method: 'POST',
                data: {
                    get_select,
                },
                success: function()
                {
                    console.log(get_select);
                    // $("#id_nama_kegiatan").val(get_select);
                }
            })
        }
    })
});
</script>
{% endblock %}