data/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='data'

urlpatterns = [
    path('', tabel_data, name="tabel_data"),
    path('tambah-data/', tambah_data, name="tambah_data"),
    path('tambah-data-kegiatan/', tambah_data_kegiatan, name="tambah_data_kegiatan"),
]

proyek/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='proyek'

urlpatterns = [
    path('', daftar_proyek, name="daftar_proyek"),
    path('tambah-proyek/', tambah_proyek, name="tambah_proyek"),
]

spkproyeksiumkt/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/profile/', account_profile, name='account_profile'),
    path('accounts/profile/', include('accounts.urls')),
    path('data/', include('data.urls')),
    path('proyek/', include('proyek.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

proyek/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import UserProfile

import string

test_list = []
test_list = list(string.ascii_uppercase)

ALPHABETS_CHOICES = (
    ('a', 'A'),
    ('b', 'B'),
    ('c', 'C')
)

# Create your models here.
class Proyek(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=False, null=True)
    nama_proyek = models.CharField(_("Nama Proyek"), max_length=255, blank=True, null=True)
    spk = models.CharField(max_length=255, blank=True, null=True)
    rab = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        ordering = ('nama_proyek',)
        verbose_name = 'Proyek'
        verbose_name_plural = 'Proyek'

    def __str__(self):
        return self.nama_proyek

proyek/forms.py
from django import forms
from django.contrib.auth.models import *
from django.utils.translation import ugettext as _

from .models import *

class Proyek_Form(forms.Form):

    user = forms.CharField(required=False, label="User:", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    nama_proyek = forms.CharField(required=False, label="Proyek:", widget=forms.TextInput(attrs={'class': "form-control"}))
    spk = forms.CharField(required=False, label="SPK:", widget=forms.TextInput(attrs={'class': "form-control"}))
    rab = forms.FloatField(required=False, label="RAB:", max_value=1000000000, min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control', 'step': "1.00"}))


class Proyek_ModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    user = forms.CharField(required=False, label="User:", widget=forms.TextInput(attrs={'class': "form-control"}))
    nama_proyek = forms.CharField(required=False, label="Proyek:", widget=forms.TextInput(attrs={'class': "form-control"}))
    spk = forms.CharField(required=False, label="SPK:", widget=forms.TextInput(attrs={'class': "form-control"}))
    rab = forms.FloatField(required=False, label="Biaya Kegiatan:", max_value=1000000000, min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control', 'step': "1.00"}))

    class Meta:
        model = Proyek
        fields = '__all__'
        # fields = ('user', 'nama_proyek', 'spk')
        widgets = {
            # 'user': forms.HiddenInput(),
            # 'tanggal_mulai': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

proyek/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render, HttpResponseRedirect, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.db.models import Sum


from .models import *
from .forms import *

from accounts.models import *

def daftar_proyek(request):
    page_title = _('Proyek')
    data_proyek = Proyek.objects.filter()

    context = {
        'page_title': page_title,
        'data_proyek': data_proyek,
    }
    return render(request,'proyek/daftar_proyek.html', context)

@login_required()
def tambah_proyek(request):
    page_title = _('Tambah Proyek')
    user_id = request.user.is_authenticated
    data_user = get_object_or_404(UserProfile, id=user_id)

    initial_value = {
        'user': data_user,
    }

    if request.method == 'POST':
        form = Proyek_Form(request.POST or None)

        if form.is_valid():
            proyek = Proyek()
            proyek.user = data_user
            proyek.nama_proyek = form.cleaned_data['nama_proyek']
            proyek.spk = form.cleaned_data['spk']
            proyek.rab = form.cleaned_data['rab']
            proyek.save()

            messages.success(request, _('Your Proyek has been save successfully.'))
            return redirect('proyek:daftar_proyek')
        else:
            messages.warning(request, form.errors)

    else:
        form = Proyek_Form(initial=initial_value)

    context = {
        'page_title': page_title,
        'form': form,
    }

    return render(request,'proyek/tambah_proyek.html', context)

templates/proyek/daftar_proyek.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6"></div>
		<div class="col-4">
			<h4>Tabel Proyek</h4>
		</div>
		<div class="col-2"></div>
	</div>
	<div class="row">
		<div class="col-md-3 col-sm-4">
			<div class="link-tiles">
				<a href="{% url 'proyek:tambah_proyek' %}" class="add_menu"><i class="fa fa-plus" aria-hidden="true"></i> Tambah Proyek</a>
			</div>
		</div>

		<div class="col-lg-8 col-md-8 col-sm-6">
			<form method="post" action="">
			{% csrf_token %}
				<table id="t_add_row" class="table table-striped table-bordered">
					<thead class="thead_light">
						<tr>
							<th class="text-center">{% trans "ID" %}</th>
							<th class="text-center">{% trans "Proyek" %}</th>
							<th class="text-center">{% trans "SPK" %}</th>
							<th class="text-center">{% trans "RAB" %}</th>
						</tr>
					</thead>
					<tbody>
						{% for item in data_proyek %}
						<tr>
							<td class="text-center">{{ item.id }}</td>
							<td>{{ item.nama_proyek }}</td>
							<td class="text-center">{{ item.spk }}</td>
							<td class="text-center">{{ item.rab|floatformat:0 }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</form>
		</div>
	</div>
</div>

{% endblock %}


{% block extra_jscript %}
{% endblock %}

templates/proyek/tambah_proyek.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-4"></div>
		<div class="col-6">
			<h4>Tambah Proyek</h4>
		</div>
		<div class="col-2"></div>
	</div>

	<div class="row">
		<div class="col-2"></div>
		<div class="col-8">
			<form action="" method="POST" id="add_billing_address_form" class="add_billing_address_form">
			{% csrf_token %}
				<div class="mb-3">
					{{ form | crispy }}
				</div>
				<button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
			</form>
		</div>
		<div class="col-2"></div>
	</div>
</div>

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


{% block extra_jscript %}
{% endblock %}