accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', account_list, name='account_list'),
    path('<str:pk>/', account_profile, name='account_profile'),
]

data/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='data'

urlpatterns = [
    path('', tabel_data, name="tabel_data"),
    path('tambah-data/', tambah_data, name="tambah_data"),
    path('tambah-data-kegiatan/', tambah_data_kegiatan, name="tambah_data_kegiatan"),
]

kegiatan/urls.py
from django.urls import path, re_path, include

from .views import *

app_name='kegiatan'

urlpatterns = [
    path('', tabel_kegiatan, name="tabel_kegiatan"),
    # path('create-forward-cpm/', create_forwardsCPM, name='create_forwardsCPM'), # create dari Python
    # path('create-backward-cpm/', create_backwardsCPM, name='create_backwardsCPM'), # create dari Python
    path('create-cpm/', create_cpm, name='create_cpm'), # create dari Python
    path('export-cpm/', export_excel, name='export_excel'),
    path('tambah-kegiatan/', tambah_kegiatan, name="tambah_kegiatan"),
    path('tabel-pert/', tabel_pert, name="tabel_pert"),
    path('tambah-pert/', tambah_pert, name="tambah_pert"),
    path('tabel-cpm/', tabel_cpm, name='tabel_cpm'),
    path('tambah-cpm/', tambah_cpm, name='tambah_cpm'),
    path('table-biaya/', tabel_estimasi_biaya, name="tabel_estimasi_biaya"),
    # path('estimasi-biaya/', estimasi_biaya, name="estimasi_biaya"),
    path('tabel-schedule/', tabel_schedule, name="tabel_schedule"), # formset 2 input progress + 1 input minggu
    path('tambah-schedule/', tambah_schedule, name="tambah_schedule"),
]

spkproyeksiumkt/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/profile/', account_profile, name='account_profile'),
    path('accounts/profile/', include('accounts.urls')),
    path('data/', include('data.urls')),
    path('proyek/', include('proyek.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

templates/base.html
{% load static %}
{% load i18n %}

<html>
    <head>
        <meta charset="utf-8" />
        <noscript>
            <meta http-equiv="Refresh" content="0; URL=/big_pipe/no-js?destination=/node" />
        </noscript>
        <link rel="canonical" href="https://panjianom.my.id/" />
        <link rel="shortlink" href="https://panjianom.my.id/" />
        <meta name="description" content="" />
        <meta name="Generator" content="Django coded by digidzine.com" />
        <meta name="MobileOptimized" content="width" />
        <meta name="HandheldFriendly" content="true" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

    <title>
        {% block head_title %}
        {% endblock %}
    </title>

    {% block extrahead %}
    {{ form.media }}
    {% endblock %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap5/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Icons  -->
    <link href="{% static 'fontawesome-free-6.0.0-web/css/all.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'icofont/icofont.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- owlcarousel Slider -->
    <link href="{% static 'owlcarousel/owl.carousel.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'owlcarousel/owl.theme.default.min.css' %}" rel="stylesheet" type="text/css" />

    <!-- Custom css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" />

    {% block extra_style %}

    {% endblock %}

    </head>

    <body class="d-flex flex-column h-100">
        {% include "header.html" %}
        {% include 'messages.html' %}

        {% block content %}
        {% include "homepage/home.html" %}
        {% endblock %}

        {% include "footer.html" %}

        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap5/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'owlcarousel/owl.carousel.js' %}" type="text/javascript"></script>


        {% block extra_jscript %}
        {% endblock %}
    </body>
</html>

templates/footer.html
{% load static %}

<footer class="footer footer-sec mt-auto py-3 bg-light">
	<diV class="container">
		<div class="row">
			<div class="col-lg-9 col-md-8 col-sm-12">
				<div class="region region-footer">
					<div id="block-footer" class="block block-superfish block-superfishfooter">
					</div>
				</div>
			</div>
			
			<div class="col-lg-3 col-md-4 col-sm-12">
			</div>
		</div>

		<div class="row copyright-sec">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<p>&copy; 2022 digiDzine. All Rights Reserved.</p>
			</div>
		</div>
	</diV>

</footer>

templates/header.html
{% load static %}
{% load i18n %}
{% load account %}

<!-- main header section start -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom box-shadow bg-light">
    <h5 class="my-0 mr-md-auto font-weight-normal text-center">
        {% if logos %}
            {% for object in logos %}
            <img class="logotenant" src="{{ object.logo_url }}">
            <a href="/" class="text-title">
                <span class="text-center">{{ titles.title }}</span>
            </a>
            {% endfor %}
        {% endif %}
    </h5>

    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link" href="/">
                            <i class="fas fa-home"></i>&nbsp;{% trans "Home" %} <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/proyek/">
                            <i class="fas fa-table"></i>&nbsp;{% trans "Proyek" %}
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/data/">
                            <i class="fa-sharp fa-solid fa-database"></i>&nbsp;{% trans "Data" %}
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kegiatan:tabel_kegiatan' %}">
                            <i class="fas fa-tasks"></i>&nbsp;{% trans "Kegiatan" %}
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fas fa-user"></i>&nbsp;{% trans "Account" %}
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="accountMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>

                        {% if user.is_authenticated %}

                        <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="accountMenu">
                            <a class="dropdown-item" href="{% url 'accounts:account_list' %}">
                                <i class="fas fa-user"></i>&nbsp;{% trans "User List" %}
                            </a>
                            <a class="dropdown-item" href="{% url 'accounts:account_profile' request.user.id %}">
                                <i class="fas fa-user-cog"></i>&nbsp;{% trans "My Account" %}
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">
                                <i class="fas fa-sign-out-alt"></i>&nbsp;{% trans "Logout" %}
                            </a>
                        </div>

                        {% else %}

                        <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="accountMenu">
                            <a class="dropdown-item" href="{% url 'account_signup' %}">
                                <i class="fas fa-user-plus"></i>&nbsp;{% trans "Register" %}
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_login' %}">
                                <i class="fas fa-sign-out-alt"></i>&nbsp;{% trans "Login" %}
                            </a>
                        </div>


                        <div class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="accountMenu">
                            <a class="dropdown-item" href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;{% trans "Login" %}</a>
                        </div>

                        {% endif %}

                    </li>
                </ul>
            </div>
        </div>
    </nav>

</div>

templates/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {{ message }}
</div>
{% endfor %}